---
abstract: 'represent an operation awaiting completion'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: 0
  Test::Identity: 0
  Test::More: 0.88
  Test::Refcount: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Future
provides:
  Future:
    file: lib/Future.pm
    version: 0.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
