---
abstract: 'represent an operation awaiting completion'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: '0'
  Test::Identity: '0'
  Test::More: '0.88'
  Test::Refcount: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Future
provides:
  Future:
    file: lib/Future.pm
    version: '0.30'
  Future::Utils:
    file: lib/Future/Utils.pm
    version: '0.30'
  Test::Future:
    file: lib/Test/Future.pm
    version: '0.30'
requires:
  Carp: '1.25'
  Test::Builder::Module: '0'
  Time::HiRes: '0'
  perl: '5.008'
resources:
  IRC: irc://irc.perl.org/#io-async
  license: http://dev.perl.org/licenses/
version: '0.30'
