---
abstract: 'represent an operation awaiting completion'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Fatal: '0'
  Test::Identity: '0'
  Test::More: '0.88'
  Test::Refcount: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Future
provides:
  Future:
    file: lib/Future.pm
    version: '0.29'
  Future::Utils:
    file: lib/Future/Utils.pm
    version: '0.29'
  Test::Future:
    file: lib/Test/Future.pm
    version: '0.29'
requires:
  Carp: '1.25'
  Test::Builder::Module: '0'
  Time::HiRes: '0'
  perl: '5.008'
resources:
  license: http://dev.perl.org/licenses/
version: '0.29'
x_breaks:
  IO::Async: '< 0.62'
  IO::Async::SSL: '< 0.14'
  Net::Async::CassandraCQL: '< 0.11'
  Net::Async::FTP: '< 0.08'
  Net::Async::HTTP: '< 0.34'
  Net::Async::WebSocket: '< 0.08'
